@echo off
setlocal EnableDelayedExpansion

REM ╔══════════════════════════════════════════════════════════════════════════╗
REM ║   x2y AV Ultimate v8.0.5  —  Windows EXE Builder                       ║
REM ║   Produces:  dist\x2yAV\x2yAV.exe  (standalone, no Python needed)      ║
REM ║   Run as Administrator for best results                                  ║
REM ╚══════════════════════════════════════════════════════════════════════════╝

title x2y AV Ultimate — EXE Builder

echo.
echo  ██╗  ██╗██████╗ ██╗   ██╗     █████╗ ██╗   ██╗
echo  ╚██╗██╔╝╚════██╗╚██╗ ██╔╝    ██╔══██╗██║   ██║
echo   ╚███╔╝  █████╔╝ ╚████╔╝     ███████║██║   ██║
echo   ██╔██╗  ╚═══██╗  ╚██╔╝      ██╔══██║╚██╗ ██╔╝
echo  ██╔╝ ██╗██████╔╝   ██║       ██║  ██║ ╚████╔╝
echo  ╚═╝  ╚═╝╚═════╝    ╚═╝       ╚═╝  ╚═╝  ╚═══╝
echo.
echo  EXE Builder  v8.0.5
echo  ══════════════════════════════════════════════
echo.

REM ── Locate Python ────────────────────────────────────────────────────────────
where python >nul 2>&1
if %errorlevel% neq 0 (
    echo  [ERROR] Python not found in PATH.
    echo          Install Python 3.10+ from https://python.org
    echo          Make sure "Add Python to PATH" is checked during install.
    echo.
    pause & exit /b 1
)

for /f "tokens=*" %%i in ('python --version 2^>^&1') do set PYVER=%%i
echo  [OK] %PYVER%

REM ── Check we are in the right directory ──────────────────────────────────────
if not exist "main.py" (
    echo  [ERROR] main.py not found.
    echo          Run this script from inside the x2y_av\ folder.
    echo.
    pause & exit /b 1
)
echo  [OK] Source files found

REM ── Create / activate virtual environment ────────────────────────────────────
if not exist "venv" (
    echo.
    echo  [*] Creating virtual environment...
    python -m venv venv
    if %errorlevel% neq 0 (
        echo  [ERROR] Failed to create venv.
        pause & exit /b 1
    )
)
call venv\Scripts\activate.bat
echo  [OK] Virtual environment ready

REM ── Upgrade pip ──────────────────────────────────────────────────────────────
echo  [*] Upgrading pip...
python -m pip install --upgrade pip --quiet

REM ── Install app dependencies ─────────────────────────────────────────────────
echo  [*] Installing app dependencies...
pip install customtkinter psutil --quiet
REM Optional extras — failures here are non-fatal
pip install yara-python pefile watchdog win10toast wmi --quiet 2>nul
echo  [OK] Dependencies installed

REM ── Install PyInstaller ──────────────────────────────────────────────────────
echo  [*] Installing PyInstaller...
pip install pyinstaller --upgrade --quiet
if %errorlevel% neq 0 (
    echo  [ERROR] PyInstaller install failed.
    pause & exit /b 1
)
echo  [OK] PyInstaller ready

REM ── Create signatures dirs if missing ────────────────────────────────────────
if not exist "signatures"       mkdir signatures
if not exist "signatures\yara"  mkdir signatures\yara

REM ── Resolve icon path ────────────────────────────────────────────────────────
set ICON_ARG=
if exist "icon.ico" (
    set ICON_ARG=--icon=icon.ico
    echo  [OK] icon.ico found — will embed in EXE
) else (
    echo  [WARN] icon.ico not found — EXE will use default Python icon
    echo         Place icon.ico next to build.bat to embed your icon.
)

REM ── Write the PyInstaller spec file ──────────────────────────────────────────
echo  [*] Writing PyInstaller spec...

(
echo # x2y AV Ultimate - PyInstaller spec
echo # Auto-generated by build.bat — do not edit manually
echo import sys, os
echo from PyInstaller.utils.hooks import collect_data_files, collect_submodules
echo.
echo block_cipher = None
echo.
echo # Gather all data files we need bundled
echo datas = [
echo     ^('theme.py',         '.'^),
echo     ^('scanner.py',       '.'^),
echo     ^('netmon.py',        '.'^),
echo     ^('persistence.py',   '.'^),
echo     ^('quarantine.py',    '.'^),
echo     ^('settings_mgr.py',  '.'^),
echo ]
echo.
echo # Bundle signatures folder if it exists
echo if os.path.isdir^('signatures'^):
echo     datas += [^('signatures', 'signatures'^)]
echo.
echo # Bundle icon files
echo for ico in ^['icon.ico', 'icon.png', 'icon_16.png', 'icon_32.png',
echo              'icon_48.png', 'icon_256.png'^]:
echo     if os.path.exists^(ico^):
echo         datas.append^(^(ico, '.'^)^)
echo.
echo # customtkinter needs its asset folder bundled
echo try:
echo     import customtkinter
echo     ctk_path = os.path.dirname^(customtkinter.__file__^)
echo     datas += [^(ctk_path, 'customtkinter'^)]
echo except ImportError:
echo     pass
echo.
echo a = Analysis^(
echo     ['main.py'],
echo     pathex=['.'],
echo     binaries=[],
echo     datas=datas,
echo     hiddenimports=[
echo         'tkinter', 'tkinter.ttk', 'tkinter.filedialog',
echo         'tkinter.messagebox', 'tkinter.simpledialog',
echo         'customtkinter',
echo         'psutil', 'psutil._pswindows',
echo         'sqlite3', '_sqlite3',
echo         'pkg_resources', 'packaging', 'packaging.version',
echo         'PIL', 'PIL.Image',
echo         'win32api', 'win32con', 'win32gui', 'winreg',
echo         'wmi', 'pythoncom', 'pywintypes',
echo         'yara', 'pefile',
echo         'scapy', 'scapy.all',
echo         'watchdog', 'watchdog.observers', 'watchdog.events',
echo         'win10toast',
echo         'plyer', 'plyer.platforms.win.notification',
echo         'urllib', 'urllib.request',
echo         'csv', 'json', 'queue', 'uuid', 'math',
echo         'hashlib', 'struct', 're', 'ipaddress',
echo         'subprocess', 'threading', 'logging',
echo     ],
echo     hookspath=[],
echo     runtime_hooks=[],
echo     excludes=['matplotlib', 'numpy', 'pandas', 'scipy',
echo               'IPython', 'jupyter', 'notebook', 'PyQt5', 'wx'],
echo     win_no_prefer_redirects=False,
echo     win_private_assemblies=False,
echo     cipher=block_cipher,
echo     noarchive=False,
echo ^)
echo.
echo pyz = PYZ^(a.pure, a.zipped_data, cipher=block_cipher^)
echo.
echo exe = EXE^(
echo     pyz,
echo     a.scripts,
echo     [],
echo     exclude_binaries=True,
echo     name='x2yAV',
echo     debug=False,
echo     bootloader_ignore_signals=False,
echo     strip=False,
echo     upx=True,
echo     console=False,
echo     disable_windowed_traceback=False,
echo     uac_admin=True,
echo     icon='icon.ico' if os.path.exists^('icon.ico'^) else None,
echo ^)
echo.
echo coll = COLLECT^(
echo     exe,
echo     a.binaries,
echo     a.zipfiles,
echo     a.datas,
echo     strip=False,
echo     upx=True,
echo     upx_exclude=[],
echo     name='x2yAV',
echo ^)
) > x2yAV.spec

echo  [OK] Spec file written

REM ── Clean previous build ─────────────────────────────────────────────────────
if exist "build"       rmdir /s /q build
if exist "dist\x2yAV"  rmdir /s /q dist\x2yAV
echo  [OK] Old build cleaned

REM ── Run PyInstaller ──────────────────────────────────────────────────────────
echo.
echo  [*] Compiling EXE — this takes 1-3 minutes...
echo  ══════════════════════════════════════════════
echo.

pyinstaller x2yAV.spec --noconfirm --clean 2>&1
set BUILD_RESULT=%errorlevel%

echo.
echo  ══════════════════════════════════════════════

if %BUILD_RESULT% neq 0 (
    echo  [ERROR] PyInstaller build FAILED.
    echo.
    echo  Common fixes:
    echo    1. Run as Administrator
    echo    2. Disable antivirus temporarily ^(it may block PyInstaller^)
    echo    3. Check output above for the specific error
    echo    4. Try: pip install pyinstaller --upgrade
    echo.
    pause & exit /b 1
)

REM ── Verify output ─────────────────────────────────────────────────────────────
if not exist "dist\x2yAV\x2yAV.exe" (
    echo  [ERROR] EXE not found at dist\x2yAV\x2yAV.exe
    pause & exit /b 1
)

REM ── Get EXE size ─────────────────────────────────────────────────────────────
for %%F in ("dist\x2yAV\x2yAV.exe") do set EXE_SIZE=%%~zF
set /a EXE_MB=%EXE_SIZE% / 1048576

REM ── Copy signatures into dist ────────────────────────────────────────────────
echo  [*] Copying signatures into dist...
if exist "signatures" (
    xcopy /E /I /Q /Y "signatures" "dist\x2yAV\signatures" >nul
    echo  [OK] Signatures bundled
)

REM ── Copy icon files into dist ─────────────────────────────────────────────────
for %%f in (icon.ico icon.png icon_16.png icon_32.png icon_48.png icon_256.png) do (
    if exist "%%f" copy /Y "%%f" "dist\x2yAV\%%f" >nul
)

REM ── Create Desktop shortcut to EXE ───────────────────────────────────────────
echo  [*] Creating Desktop shortcut...
set EXE_PATH=%~dp0dist\x2yAV\x2yAV.exe
set SHORTCUT=%USERPROFILE%\Desktop\x2y AV Ultimate.lnk
set ICO_PATH=%~dp0dist\x2yAV\icon.ico

powershell -NoProfile -Command ^
  "$ws = New-Object -ComObject WScript.Shell; ^
   $s  = $ws.CreateShortcut('%SHORTCUT%'); ^
   $s.TargetPath      = '%EXE_PATH%'; ^
   $s.WorkingDirectory= '%~dp0dist\x2yAV'; ^
   $s.Description     = 'x2y AV Ultimate v8.0.5'; ^
   if (Test-Path '%ICO_PATH%') { $s.IconLocation = '%ICO_PATH%' }; ^
   $s.Save()" 2>nul

if exist "%SHORTCUT%" (
    echo  [OK] Desktop shortcut created
) else (
    echo  [WARN] Could not create shortcut ^(run as admin to fix^)
)

REM ── Optional: download initial signatures ─────────────────────────────────────
echo.
set /p DLSIGS="Download initial MalwareBazaar signatures now? [Y/N]: "
if /i "!DLSIGS!"=="Y" (
    echo  [*] Downloading signatures ^(this may take a minute^)...
    cd dist\x2yAV
    x2yAV.exe --download-sigs 2>nul
    REM Fallback: run python if EXE flag not supported yet
    python -c "import sys; sys.path.insert(0,'%~dp0'); from scanner import ScannerEngine, update_malwarebazaar; db=ScannerEngine().db; n=update_malwarebazaar(db,cb=print); print(f'Downloaded {n} hashes')" 2>nul
    cd ..\..
)

REM ── Summary ───────────────────────────────────────────────────────────────────
echo.
echo  ╔══════════════════════════════════════════════════════════════╗
echo  ║   BUILD SUCCESSFUL                                           ║
echo  ╠══════════════════════════════════════════════════════════════╣
echo  ║                                                              ║
echo  ║   EXE:     dist\x2yAV\x2yAV.exe  ^(%EXE_MB% MB^)               ║
echo  ║   Folder:  dist\x2yAV\                                       ║
echo  ║   Shortcut: Desktop  →  x2y AV Ultimate                     ║
echo  ║                                                              ║
echo  ║   TO DISTRIBUTE:                                             ║
echo  ║     Zip the entire  dist\x2yAV\  folder.                    ║
echo  ║     The EXE alone will NOT run — it needs its folder.       ║
echo  ║                                                              ║
echo  ║   TO MAKE A SINGLE-FILE EXE (larger, slower startup):       ║
echo  ║     Edit x2yAV.spec — change  exclude_binaries=True         ║
echo  ║     to  exclude_binaries=False  and remove the COLLECT block ║
echo  ║     then re-run:  pyinstaller x2yAV.spec --noconfirm        ║
echo  ║                                                              ║
echo  ╚══════════════════════════════════════════════════════════════╝
echo.

REM ── Offer to launch ──────────────────────────────────────────────────────────
set /p LAUNCH="Launch x2y AV now? [Y/N]: "
if /i "!LAUNCH!"=="Y" (
    start "" "dist\x2yAV\x2yAV.exe"
)

echo.
pause