# x2y AV Ultimate - PyInstaller spec
# Auto-generated by build.bat — do not edit manually
import sys, os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# Gather all data files we need bundled
datas = [
    ('theme.py',         '.'),
    ('scanner.py',       '.'),
    ('netmon.py',        '.'),
    ('persistence.py',   '.'),
    ('quarantine.py',    '.'),
    ('settings_mgr.py',  '.'),
]

# Bundle signatures folder if it exists
if os.path.isdir('signatures'):
    datas += [('signatures', 'signatures')]

# Bundle icon files
for ico in ['icon.ico', 'icon.png', 'icon_16.png', 'icon_32.png',
             'icon_48.png', 'icon_256.png']:
    if os.path.exists(ico):
        datas.append((ico, '.'))

# customtkinter needs its asset folder bundled
try:
    import customtkinter
    ctk_path = os.path.dirname(customtkinter.__file__)
    datas += [(ctk_path, 'customtkinter')]
except ImportError:
    pass

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'tkinter', 'tkinter.ttk', 'tkinter.filedialog',
        'tkinter.messagebox', 'tkinter.simpledialog',
        'customtkinter',
        'psutil', 'psutil._pswindows',
        'sqlite3', '_sqlite3',
        'pkg_resources', 'packaging', 'packaging.version',
        'PIL', 'PIL.Image',
        'win32api', 'win32con', 'win32gui', 'winreg',
        'wmi', 'pythoncom', 'pywintypes',
        'yara', 'pefile',
        'scapy', 'scapy.all',
        'watchdog', 'watchdog.observers', 'watchdog.events',
        'win10toast',
        'plyer', 'plyer.platforms.win.notification',
        'urllib', 'urllib.request',
        'csv', 'json', 'queue', 'uuid', 'math',
        'hashlib', 'struct', 're', 'ipaddress',
        'subprocess', 'threading', 'logging',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'pandas', 'scipy',
              'IPython', 'jupyter', 'notebook', 'PyQt5', 'wx'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='x2yAV',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    uac_admin=True,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='x2yAV',
)
